server {
    listen 80;

    resolver 127.0.0.11 valid=5s ipv6=off;

    root /usr/share/nginx/html;
    index index.html;

    # Dev mode: no caching for JS/CSS so updates are reflected immediately
    location ~* \.(js|css)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires 0;
        try_files $uri =404;
    }

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ /index.html;
    }

    set $be_upstream http://backend:8000;

    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $be_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
